on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: arcdemo321.azurecr.io
        username: ${{ secrets.acr_arcdemo321_username }}
        password: ${{ secrets.acr_arcdemo321_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t arcdemo321.azurecr.io/aksan:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push arcdemo321.azurecr.io/aksan:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksan_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksan94bd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksan94bd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksan94bd
        container-registry-url: arcdemo321.azurecr.io
        container-registry-username: ${{ secrets.acr_arcdemo321_username }}
        container-registry-password: ${{ secrets.acr_arcdemo321_password }}
        secret-name: aksandockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksan94bd
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          arcdemo321.azurecr.io/aksan:${{ github.sha }}
        imagepullsecrets: |
          aksandockerauth
